include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

variables:
  STACK: log
  IMAGE_NAME: fluent/fluentd
  IMAGE_TAG: v1.3
  COMPOSE_FILE: docker-compose.yml

.deploy:
  script:
    - >
      deploy.sh IMAGE_NAME=${IMAGE_NAME} IMAGE_TAG=${IMAGE_TAG} ES_HOSTS=${ES_HOSTS} ES_USER=${ES_USER}
      ES_PASS=${ES_PASS}
