version: '3.5'

services:
  fluentd:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - ES_HOSTS
      - ES_USER
      - ES_PASS
    networks:
      - log-net
      - elastic-net
    configs:
      - source: fluent-conf
        target: /fluentd/etc/fluent.conf
    logging:
      driver: json-file
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          memory: 64M

networks:
  log-net:
    name: ${LOG_NET_NAME:-log-net}
    driver: overlay
    attachable: ${LOG_NET_ATTACHABLE:-true}

  elastic-net:
    name: ${ELASTIC_NET_NAME:-elastic6-net}
    external: true

configs:
  fluent-conf:
    name: ${FLUENT_CONF_NAME:-fluent-conf}
    file: ./conf/fluent.conf
