version: '3.5'

services:
  fluentd:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - ES_HOSTS
      - ES_USER
      - ES_PASS
    networks:
      log-net:
        aliases:
          - fluentd
      elastic-net:
    secrets:
      - source: fluent-conf
        target: /fluentd/etc/fluent.conf
    logging:
      driver: json-file
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          memory: 103M

networks:
  log-net:
    name: log-net
    driver: overlay
    attachable: true

  elastic-net:
    external: true

secrets:
  fluent-conf:
    file: ./conf/fluent.conf
